# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kjXtZhWUX63ZWVzTFOWTrGzqbVLg1mhu
"""

# 3. Install PyTorch Geometric core package
!pip install -q torch-geometric

import os
import torch

# 1. Automatically detect PyTorch and CUDA versions in Colab
TORCH = torch.__version__.split('+')[0]
CUDA = 'cu' + torch.version.cuda.replace('.', '') if torch.cuda.is_available() else 'cpu'

print(f"PyTorch version: {TORCH}")
print(f"CUDA version: {CUDA}")





import torch
import torch.nn.functional as F
from torch_geometric.datasets import Planetoid
from torch_geometric.transforms import NormalizeFeatures
from torch_geometric.nn import GATConv

# 1. Load the Cora Dataset with normalized node features
dataset = Planetoid(root='data/Planetoid', name='Cora', transform=NormalizeFeatures())
data = dataset[0]  # Get the single citation graph



print(f"Cora Graph Info:")
print(f"Nodes: {data.num_nodes} | Edges: {data.num_edges}")
print(f"Features per node: {dataset.num_features} | Classes: {dataset.num_classes}")

import torch
import torch.nn.functional as F
from torch_geometric.nn import GATConv

HIDDEN_FEATURES = 32
NUM_HEADS = 4

class cora(torch.nn.Module):
    def __init__(self, num_features, hidden_features, out_features, num_head):
        super().__init__()
        self.conv1 = GATConv(in_channels=num_features, out_channels=hidden_features, heads=num_head, dropout=0.6)
        self.conv2 = GATConv(in_channels=hidden_features * num_head, out_channels=out_features, dropout=0.4, concat=False)

    def forward(self, input_feature, edge_index, return_att=False):
        x = F.dropout(input=input_feature, p=0.6, training=self.training)

        # Αν ζητήσουμε τα weights, παίρνουμε τα attention weights από το 1ο layer (conv1)
        if return_att:
            x, (att_edge_index, alpha) = self.conv1(x, edge_index, return_attention_weights=True)
        else:
            x = self.conv1(x, edge_index)

        x = F.elu(x)
        x = F.dropout(input=x, p=0.6, training=self.training)
        x = self.conv2(x, edge_index)

        if return_att:
            return x, att_edge_index, alpha
        return x

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = cora(data.num_features, HIDDEN_FEATURES, dataset.num_classes, NUM_HEADS).to(device)
data = data.to(device)

criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.01, weight_decay=5e-4)

def train():
    model.train()
    optimizer.zero_grad()
    out = model.forward(data.x, data.edge_index)
    loss = criterion(out[data.train_mask], data.y[data.train_mask])
    loss.backward()
    optimizer.step()
    return loss.item()



@torch.no_grad()
def test():
  model.eval()
  out = model.forward(data.x, data.edge_index)
  pred = out.argmax(dim=1)

  accuracy = []
  for mask in [data.train_mask, data.val_mask, data.test_mask]:
    correct = (pred[mask] == data.y[mask]).sum()
    ratio = (int(correct) / int(mask.sum()))
    accuracy.append(ratio)
  return accuracy



# Run training across 200 epochs
for epoch in range(1, 201):
    loss = train()
    if epoch % 20 == 0:
        train_acc, val_acc, test_acc = test()
        print(f"Epoch {epoch:03d} | Loss: {loss:.4f} | Train Acc: {train_acc*100:.1f}% | Val Acc: {val_acc*100:.1f}% | Test Acc: {test_acc*100:.1f}%")

import matplotlib.pyplot as plt
from sklearn.manifold import TSNE

# 1. Extract learned hidden embeddings right before the final output layer
model.eval()
with torch.no_grad():
    # Pass features through Layer 1 (8 heads * 8 hidden = 64 dimensions)
    x = F.dropout(data.x, p=0.6, training=False)
    embeddings = model.conv1(x, data.edge_index)  # Shape: [2708, 64]

# Move data to CPU for Scikit-Learn & Matplotlib
embeddings_cpu = embeddings.cpu().numpy()
labels_cpu = data.y.cpu().numpy()

# 2. Reduce 64-dimensional embeddings down to 2D using t-SNE
print("Computing 2D t-SNE projection...")
tsne = TSNE(n_components=2, perplexity=30, random_state=42)
embeddings_2d = tsne.fit_transform(embeddings_cpu)

# 3. Plot the clusters
plt.figure(figsize=(10, 8), dpi=150)

# The Cora dataset has 7 subject classes
class_names = [
    'Theory', 'Reinforcement Learning', 'Genetic Algorithms',
    'Neural Networks', 'Probabilistic Methods', 'Case Based', 'Rule Learning'
]

scatter = plt.scatter(
    embeddings_2d[:, 0],
    embeddings_2d[:, 1],
    c=labels_cpu,
    cmap='tab10',
    s=15,
    alpha=0.8
)

plt.legend(
    handles=scatter.legend_elements()[0],
    labels=class_names,
    title="Cora Paper Topics",
    bbox_to_anchor=(1.05, 1),
    loc='upper left'
)

plt.title("GAT Node Embeddings Projection (t-SNE on Cora)", fontsize=14, fontweight='bold')
plt.xlabel("t-SNE Dimension 1")
plt.ylabel("t-SNE Dimension 2")
plt.grid(True, linestyle='--', alpha=0.3)

plt.tight_layout()
plt.savefig("gat_cora_embeddings.png", dpi=300)
plt.show()

!pip install -q pyvis

import networkx as nx
from pyvis.network import Network
from torch_geometric.utils import k_hop_subgraph

# 1. Get model predictions on the whole graph
model.eval()
with torch.no_grad():
    out = model(data.x, data.edge_index)
    preds = out.argmax(dim=1).cpu()

# 2. Extract a clean sub-graph snippet (e.g., 2-hop neighborhood around paper #0)
target_paper_id = 0
subset_nodes, subset_edges, mapping, edge_mask = k_hop_subgraph(
    node_idx=target_paper_id,
    num_hops=2,
    edge_index=data.edge_index,
    relabel_nodes=False
)

print(f"Extracted snippet centered at Paper #{target_paper_id}:")
print(f"Nodes in view: {len(subset_nodes)} | Edges in view: {subset_edges.size(1)}")

# 3. Class Names & Distinct Colors for Visualization
class_names = [
    'Theory', 'Reinforcement Learning', 'Genetic Algorithms',
    'Neural Networks', 'Probabilistic Methods', 'Case Based', 'Rule Learning'
]
class_colors = ['#e41a1c', '#377eb8', '#4daf4a', '#984ea3', '#ff7f00', '#ffff33', '#a65628']

# 4. Build PyVis Network Graph
net = Network(height="600px", width="100%", bgcolor="#222222", font_color="white", notebook=True)

# Add Nodes with Custom Styling & Hover Tooltips
for node_id in subset_nodes.tolist():
    true_label = class_names[data.y[node_id].item()]
    pred_label = class_names[preds[node_id].item()]
    is_correct = (true_label == pred_label)

    color = class_colors[preds[node_id].item()]

    # Highlight the central paper node with a larger size
    size = 25 if node_id == target_paper_id else 15

    # Hover text showing Node Details
    tooltip = (
        f"<b>Paper ID:</b> {node_id}<br>"
        f"<b>Predicted Class:</b> {pred_label}<br>"
        f"<b>True Class:</b> {true_label}<br>"
        f"<b>Status:</b> {'Correct' if is_correct else 'Misclassified'}"
    )

    net.add_node(
        node_id,
        label=f"Paper {node_id}",
        title=tooltip,
        color=color,
        size=size
    )

# Add Citation Edges
src_nodes = subset_edges[0].tolist()
dst_nodes = subset_edges[1].tolist()
for src, dst in zip(src_nodes, dst_nodes):
    net.add_edge(src, dst, color="#888888")

# Configure physics layout for smooth interactive dragging
net.force_atlas_2based()

# Save interactive HTML file
html_filename = "cora_gat_interactive.html"
net.show(html_filename)
print(f"\nSaved interactive graph to '{html_filename}'!")

import networkx as nx
import matplotlib.pyplot as plt

# 1. Εκτέλεση του μοντέλου σου με return_att=True
model.eval()
with torch.no_grad():
    out, att_edge_index, alpha = model(data.x, data.edge_index, return_att=True)

# Παίρνουμε το μέσο όρο των 4 heads που όρισες (NUM_HEADS = 4)
alpha_mean = alpha.mean(dim=1).squeeze()

# 2. Επιλογή Κεντρικού Κόμβου
target_node = 0  # Μπορείς να βάλεις όποιον κόμβο θέλεις (0 - 2707)

# Βρίσκουμε τις ακμές που συνδέονται ΜΟΝΟ με τον target_node
mask = (att_edge_index[0] == target_node) | (att_edge_index[1] == target_node)
sub_edges = att_edge_index[:, mask]
sub_weights = alpha_mean[mask]

# 3. Δημιουργία Graph & Υπολογισμός Ποσοστών (%)
G = nx.DiGraph()
total_weight = sub_weights.sum().item() if sub_weights.sum().item() > 0 else 1.0

edge_labels = {}
for i in range(sub_edges.shape[1]):
    src = sub_edges[0, i].item()
    dst = sub_edges[1, i].item()
    w = sub_weights[i].item()

    # Υπολογισμός ποσοστού % επί του συνόλου της προσοχής του κόμβου
    percentage = (w / total_weight) * 100

    G.add_edge(src, dst, weight=w)
    edge_labels[(src, dst)] = f"{percentage:.1f}%"

# 4. Σχεδίαση του Γράφου
plt.figure(figsize=(10, 8), dpi=150)
pos = nx.spring_layout(G, seed=42)  # Σταθερή διάταξη

# Πάχος γραμμών ανάλογα με το weight
weights = [G[u][v]['weight'] for u, v in G.edges()]
max_w = max(weights) if max(weights) > 0 else 1
edge_widths = [(w / max_w) * 5 + 1.0 for w in weights]

# Χρώματα: Κόκκινο ο κεντρικός κόμβος, Μπλε οι γείτονες
node_colors = ['#E63946' if node == target_node else '#457B9D' for node in G.nodes()]

# Κόμβοι & Labels Κόμβων
nx.draw_networkx_nodes(G, pos, node_size=800, node_color=node_colors)
nx.draw_networkx_labels(G, pos, font_color='white', font_weight='bold', font_size=10)

# Ακμές
nx.draw_networkx_edges(
    G, pos,
    width=edge_widths,
    edge_color='#1D3557',
    arrowsize=15,
    connectionstyle="arc3,rad=0.1"
)

# Ετικέτες Ποσοστών πάνω στις Ακμές
nx.draw_networkx_edge_labels(
    G, pos,
    edge_labels=edge_labels,
    font_color='#D62828',
    font_weight='bold',
    font_size=9,
    label_pos=0.3
)

plt.title(f"GAT Attention Distribution (%) around Node #{target_node}", fontsize=13, fontweight='bold')
plt.axis('off')
plt.tight_layout()
plt.show()









data.train_mask.sum()



























































